# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  peer0.spwatersupply.com:
  peer1.spwatersupply.com:

networks:
  new:

services:

  peer0.spwatersupply.com:
    container_name: peer0.spwatersupply.com
    extends:
      file: base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.spwatersupply.com
      - CORE_PEER_ADDRESS=peer0.spwatersupply.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.spwatersupply.com:7051
      - CORE_PEER_LOCALMSPID=SparkMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./org3-artifacts/crypto-config/peerOrganizations/spwatersupply.com/peers/peer0.spwatersupply.com/msp:/etc/hyperledger/fabric/msp
        - ./org3-artifacts/crypto-config/peerOrganizations/spwatersupply.com/peers/peer0.spwatersupply.com/tls:/etc/hyperledger/fabric/tls
        - peer0.spwatersupply.com:/var/hyperledger/production
    ports:
      - 89:7051
      - 90:7053
    networks:
      - new

  peer1.spwatersupply.com:
    container_name: peer1.spwatersupply.com
    extends:
      file: base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.spwatersupply.com
      - CORE_PEER_ADDRESS=peer1.spwatersupply.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.spwatersupply.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.spwatersupply.com:7051
      - CORE_PEER_LOCALMSPID=SparkMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./org3-artifacts/crypto-config/peerOrganizations/spwatersupply.com/peers/peer1.spwatersupply.com/msp:/etc/hyperledger/fabric/msp
        - ./org3-artifacts/crypto-config/peerOrganizations/spwatersupply.com/peers/peer1.spwatersupply.com/tls:/etc/hyperledger/fabric/tls
        - peer1.spwatersupply.com:/var/hyperledger/production
    ports:
      - 91:7051
      - 92:7053
    networks:
      - new


  Org3cli:
    container_name: Org3cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=INFO
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=Org3cli
      - CORE_PEER_ADDRESS=peer0.spwatersupply.com:7051
      - CORE_PEER_LOCALMSPID=SparkMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/spwatersupply.com/peers/peer0.spwatersupply.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/spwatersupply.com/peers/peer0.spwatersupply.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/spwatersupply.com/peers/peer0.spwatersupply.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/spwatersupply.com/users/Admin@spwatersupply.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./org3-artifacts/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
    depends_on:
      - peer0.spwatersupply.com
      - peer1.spwatersupply.com
    networks:
      - new
