# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  ca.debutinfotech.com:
  peer0.debutinfotech.com:
  peer1.debutinfotech.com:
  peer0.axisbank.com:
  peer1.axisbank.com:

networks:
  debutAxisNetwork:

services:

  ca.debutinfotech.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: ca.debutinfotech.com
    container_name: DebutInfotechCAOrderer
    networks:
      - debutAxisNetwork

  peer0.debutinfotech.com:
    container_name: DebutInfotechPeer0
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.debutinfotech.com
    networks:
      - debutAxisNetwork

  peer1.debutinfotech.com:
    container_name: DebutInfotechPeer1
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.debutinfotech.com
    networks:
      - debutAxisNetwork

  peer0.axisbank.com:
    container_name: AxisBankPeer0
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.axisbank.com
    networks:
      - debutAxisNetwork

  peer1.axisbank.com:
    container_name: AxisBankPeer1
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.axisbank.com
    networks:
      - debutAxisNetwork

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.debutinfotech.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/debutinfotech.com/peers/peer0.debutinfotech.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/debutinfotech.com/peers/peer0.debutinfotech.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/debutinfotech.com/peers/peer0.debutinfotech.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/debutinfotech.com/users/Admin@debutinfotech.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - ca.debutinfotech.com
      - peer0.debutinfotech.com
      - peer1.debutinfotech.com
      - peer0.axisbank.com
      - peer1.axisbank.com
    networks:
      - debutAxisNetwork
