# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  hr.debut.com:
    container_name: hr.debut.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=DebutOrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/debut.com/orderers/hr.debut.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/debut.com/orderers/hr.debut.com/tls/:/var/hyperledger/orderer/tls
    - hr.debut.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.debut.com:
    container_name: peer0.debut.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.debut.com
      - CORE_PEER_ADDRESS=peer0.debut.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.debut.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.debut.com:7051
      - CORE_PEER_LOCALMSPID=DebutMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/debut.com/peers/peer0.debut.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/debut.com/peers/peer0.debut.com/tls:/etc/hyperledger/fabric/tls
        - peer0.debut.com:/var/hyperledger/production
    ports:
      - 81:7051
      - 82:7053

  peer1.debut.com:
    container_name: peer1.debut.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.debut.com
      - CORE_PEER_ADDRESS=peer1.debut.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.debut.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.debut.com:7051
      - CORE_PEER_LOCALMSPID=DebutMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/debut.com/peers/peer1.debut.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/debut.com/peers/peer1.debut.com/tls:/etc/hyperledger/fabric/tls
        - peer1.debut.com:/var/hyperledger/production
    ports:
      - 83:7051
      - 84:7053

  peer0.axisbank.com:
    container_name: peer0.axisbank.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.axisbank.com
      - CORE_PEER_ADDRESS=peer0.axisbank.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.axisbank.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.axisbank.com:7051
      - CORE_PEER_LOCALMSPID=AxisMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/axisbank.com/peers/peer0.axisbank.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/axisbank.com/peers/peer0.axisbank.com/tls:/etc/hyperledger/fabric/tls
        - peer0.axisbank.com:/var/hyperledger/production
    ports:
      - 85:7051
      - 86:7053

  peer1.axisbank.com:
    container_name: peer1.axisbank.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.axisbank.com
      - CORE_PEER_ADDRESS=peer1.axisbank.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.axisbank.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.axisbank.com:7051
      - CORE_PEER_LOCALMSPID=AxisMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/axisbank.com/peers/peer1.axisbank.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/axisbank.com/peers/peer1.axisbank.com/tls:/etc/hyperledger/fabric/tls
        - peer1.axisbank.com:/var/hyperledger/production
    ports:
      - 87:7051
      - 88:7053
