# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  ca.debutinfotech.com:
    container_name: DebutInfotechCAOrderer
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=DebutOrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/debutinfotech.com/orderers/ca.debutinfotech.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/debutinfotech.com/orderers/ca.debutinfotech.com/tls/:/var/hyperledger/orderer/tls
    - ca.debutinfotech.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.debutinfotech.com:
    container_name: DebutInfotechPeer0
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.debutinfotech.com
      - CORE_PEER_ADDRESS=peer0.debutinfotech.com:1051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.debutinfotech.com:2051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.debutinfotech.com:1051
      - CORE_PEER_LOCALMSPID=DebutMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/debutinfotech.com/peers/peer0.debutinfotech.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/debutinfotech.com/peers/peer0.debutinfotech.com/tls:/etc/hyperledger/fabric/tls
        - peer0.debutinfotech.com:/var/hyperledger/production
    ports:
      - 999:7051
      - 21212:7053

  peer1.debutinfotech.com:
    container_name: DebutInfotechPeer1
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.debutinfotech.com
      - CORE_PEER_ADDRESS=peer1.debutinfotech.com:2051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.debutinfotech.com:2051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.debutinfotech.com:1051
      - CORE_PEER_LOCALMSPID=DebutMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/debutinfotech.com/peers/peer1.debutinfotech.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/debutinfotech.com/peers/peer1.debutinfotech.com/tls:/etc/hyperledger/fabric/tls
        - peer1.debutinfotech.com:/var/hyperledger/production
    ports:
      - 2051:7051
      - 2053:7053

  peer0.axisbank.com:
    container_name: AxisBankPeer0
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.axisbank.com
      - CORE_PEER_ADDRESS=peer0.axisbank.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.axisbank.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.axisbank.com:10051
      - CORE_PEER_LOCALMSPID=AxisMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/axisbank.com/peers/peer0.axisbank.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/axisbank.com/peers/peer0.axisbank.com/tls:/etc/hyperledger/fabric/tls
        - peer0.axisbank.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053

  peer1.axisbank.com:
    container_name: AxisBankPeer1
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.axisbank.com
      - CORE_PEER_ADDRESS=peer1.axisbank.com:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.axisbank.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.axisbank.com:9051
      - CORE_PEER_LOCALMSPID=AxisMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/axisbank.com/peers/peer1.axisbank.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/axisbank.com/peers/peer1.axisbank.com/tls:/etc/hyperledger/fabric/tls
        - peer1.axisbank.com:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053
